export const mockProducts = [
  {
    id: 1,
    productName: "Blender's Pride",
    brand: "Blender's Pride",
    category: "whisky",
    size: 750,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 45,
    shopId: 1,
    shopName: "Mumbai Central",
    price: 1200,
    mrp: 1350,
    lastUpdated: "2024-01-15",
  },
  {
    id: 2,
    productName: "Royal Stag",
    brand: "Royal Stag",
    category: "whisky",
    size: 375,
    sizeUnit: "ml",
    bottleType: "half",
    closingStock: 28,
    shopId: 1,
    shopName: "Mumbai Central",
    price: 650,
    mrp: 720,
    lastUpdated: "2024-01-15",
  },
  {
    id: 3,
    productName: "Kingfisher Premium",
    brand: "Kingfisher",
    category: "beer",
    size: 650,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 120,
    shopId: 2,
    shopName: "Delhi NCR",
    price: 120,
    mrp: 150,
    lastUpdated: "2024-01-15",
  },
  {
    id: 4,
    productName: "Smirnoff Vodka",
    brand: "Smirnoff",
    category: "vodka",
    size: 750,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 32,
    shopId: 2,
    shopName: "Delhi NCR",
    price: 900,
    mrp: 1050,
    lastUpdated: "2024-01-15",
  },
  {
    id: 5,
    productName: "Old Monk Rum",
    brand: "Old Monk",
    category: "rum",
    size: 750,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 56,
    shopId: 3,
    shopName: "Bangalore South",
    price: 450,
    mrp: 550,
    lastUpdated: "2024-01-15",
  },
  {
    id: 6,
    productName: "McDowell's No.1",
    brand: "McDowell's",
    category: "whisky",
    size: 90,
    sizeUnit: "ml",
    bottleType: "90ml",
    closingStock: 0,
    shopId: 4,
    shopName: "Pune West",
    price: 90,
    mrp: 110,
    lastUpdated: "2024-01-15",
  },
  {
    id: 7,
    productName: "Bacardi White Rum",
    brand: "Bacardi",
    category: "rum",
    size: 750,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 18,
    shopId: 4,
    shopName: "Pune West",
    price: 1100,
    mrp: 1250,
    lastUpdated: "2024-01-15",
  },
  {
    id: 8,
    productName: "Tuborg Strong",
    brand: "Tuborg",
    category: "beer",
    size: 650,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 65,
    shopId: 5,
    shopName: "Hyderabad Central",
    price: 140,
    mrp: 165,
    lastUpdated: "2024-01-15",
  },
  {
    id: 9,
    productName: "Imperial Blue",
    brand: "Imperial Blue",
    category: "whisky",
    size: 375,
    sizeUnit: "ml",
    bottleType: "half",
    closingStock: 42,
    shopId: 5,
    shopName: "Hyderabad Central",
    price: 600,
    mrp: 680,
    lastUpdated: "2024-01-15",
  },
  {
    id: 10,
    productName: "Teachers Whisky",
    brand: "Teachers",
    category: "whisky",
    size: 750,
    sizeUnit: "ml",
    bottleType: "full",
    closingStock: 15,
    shopId: 1,
    shopName: "Mumbai Central",
    price: 950,
    mrp: 1100,
    lastUpdated: "2024-01-15",
  },
];
